### ISSUE TITLE
Explanation of Usage - Documentation

### ISSUE THREAD

**Issue by phaicm** [Blumster/TNLPacketAnalyzer#1]
Hello, 

What format does the input files must be in? Currently testing with a text file (test.txt) with a 1 line of hexadecimal values of a packet dump. Would you be able to explain what format do I need to provide the analyzer with?

**Comment by Blumster** [comment]
Hi,

The tools requires a text file with every row containing a packet created by the TNL framework. Empty rows are skipped.
The format is like the output of BitConverter.ToString(byte[]):
Example input file: (It's random data, not a valid file!)
04-A0-CB-88-4F-12
05-FF-FF-1A-AB-CD-EF-DE-AD-BE-EF
etc...

What game's/program's communication do you want to analyze with this?
It might? work nonetheless, but if you are not trying it with Auto Assault, it might crash or just not write a lot of info about the RPC calls, just the basic packets TNL sends.
As you can see here:
https://github.com/Blumster/TNLPacketAnalyzer/blob/master/TNLPacketAnalyzer.RUN/Analyzer.cs#L344
It uses stuff from the Auto Assault's TNL layer sometimes even in the case of default packets, so be advised: this was written to analyze Auto Assault's TNL communication in order to find bugs, as I had an issue with TNL while I was rewriting it to C#.

**Comment by phaicm** [comment]
Thanks for the response. 

We are trying to analyze an old Virtools game using OpenTNL. Based on the dump, there are some custom RPC implementations.


```
RPC_SBClientConnection_sBroadcastChatMessage
RPC_SBClientConnection_cSendGameEvent
RPC_SBClientConnection_cSetSimulatedNetParams
RPC_SBClientConnection_s2cResetGame


    RPC_SBMasterServerInterface_c2mQueryGameTypes
    RPC_SBMasterServerInterface_m2cQueryGameTypesResponse
    RPC_SBMasterServerInterface_c2mQueryServers
RPC_SBMasterServerInterface_m2cQueryServersResponseEnd
    RPC_SBMasterServerInterface_m2cQueryServersResponse
    RPC_SBMasterServerInterface_c2mRequestArrangedConnection
RPC_SBMasterServerInterface_c2mRequestMatchMaking
RPC_SBMasterServerInterface_c2mRequestMatchMakingByRank
RPC_SBMasterServerInterface_c2mCancelMatchMakingRequest
    RPC_SBMasterServerInterface_m2cClientRequestedArrangedConnection
    RPC_SBMasterServerInterface_c2mAcceptArrangedConnection
    RPC_SBMasterServerInterface_c2mRejectArrangedConnection
    RPC_SBMasterServerInterface_m2cArrangedConnectionAccepted
    RPC_SBMasterServerInterface_m2cArrangedConnectionRejected
    RPC_SBMasterServerInterface_c2mUpdateServerStatus
RPC_SBMasterServerInterface_c2mRequestGameId
RPC_SBMasterServerInterface_m2cReturnGameId
RPC_SBMasterServerInterface_m2cGetPlayerCount
RPC_SBMasterServerInterface_c2mSendPlayerCount
RPC_SBMasterServerInterface_s2mUpdatePlayerCount
RPC_SBMasterServerInterface_s2mRemoveConnAssigned
RPC_SBMasterServerInterface_m2cSendMatchMakingMsg


RPC_SBAvatarConnection_c2sSendCharacterInfo
RPC_SBAvatarConnection_c2sSendCharacterStats
RPC_SBAvatarConnection_c2sSendCharacterAttackStats


    RPC_GhostConnection_rpcStartGhosting
    RPC_GhostConnection_rpcReadyForNormalGhosts
    RPC_GhostConnection_rpcEndGhosting
```

Anything tabbed is something I suspect is default implementation from openTNL. 

Does your program require the packets to be in order starting from PacketID 0 (handleConnectChallengeRequest)? 

I've tried one packet: 

```02-76-a9-b2-f3-fc-46-26-80-75-d1-1b-0e-3a-68-c4-22-e1-dc-25-53-11-00-00-00-2c-9f-06-00-ba-a6-5b-e7-88-31-8d-70-65-83-b7-e9-9b-f4-b6-9a-12-3d-06-56-12-00-00-00-00-00-00-00-b0-00-00-00-10-61-9a-b6-cb-49-92```

and the debug output resulted in:

```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TNLPacketAnalyzer.RUN.Reader.PeekBit(Int32 bit) in Reader.cs:line 22
   at TNLPacketAnalyzer.RUN.Reader.ReadBit() in Reader.cs:line 27
   at TNLPacketAnalyzer.RUN.Reader.ReadInt(Int64 bits) in Reader.cs:line 39
   at TNLPacketAnalyzer.RUN.Analyzer.AnalyzeConnectRequestPacket(StringBuilder sb) in Analyzer.cs:line 345
   at TNLPacketAnalyzer.RUN.Analyzer.AnalyzeConnectionPacket(StringBuilder sb) in Analyzer.cs:line 256
   at TNLPacketAnalyzer.RUN.Analyzer.Run() in Analyzer.cs:line 22
   at TNLPacketAnalyzer.RUN.Program.Main(String[] args) in Program.cs:line 41
```


Any suggestions you can offer would be much appreciated.

**Comment by Blumster** [comment]
No order is needed, it just creates a textual representation of the content that is in the packet. You can send the same packet a million times, resulting in the same text representation.

Like I've said, this is tailored to Auto Assault. The error is it tries to read more from the array, than there is:
https://github.com/Blumster/TNLPacketAnalyzer/blob/master/TNLPacketAnalyzer.RUN/Analyzer.cs#L345

In this line it is already reading stuff that is Auto Assault's TNLConnection specific.

You will have to align the analyzer with your TNL implementation.
E.g.:
- Remove the TNLConnection part, as that is AA related.
- Implement your own connection's reading
   - Note: You use TNL by defining a class that exists in both the client and the server and 2 instances of that class (1 in client, 1 in server) communicates. Those might have extra fields read, like in the case of TNL connection, where it crashes. Over reading is crashing, under reading does not, but it might not show some info at the end of the packet.
- Replace AA's RPC implementations and implement your own RPC reading per RPC.
- And so on. I'm not sure about every step as it could be game specific.

**Comment by phaicm** [comment]
Ah, didn't know TNLConnection::ConnectRequest was tailored towards AA. 

Makes sense. Cheers for all the help!.
